config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :edit, :update] do
      collection do
      get ':id/rooms_list' => 'users#rooms_list'
      get ':id/friends_list' => 'users#friends_list'
    end
  end
  root to: 'top#index'
  resources :rooms, only: [:new, :create, :show, :edit, :update] do
    resources :messages, only: [:create]
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :room

  validates_presence_of :user_id, :text, :room_id

end

app/models/room.rb
class Room < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :messages, ->{ order("created_at DESC") }
  validates :key, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"}
  validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]

  def full_profile?
    avatar? && name? && user_id?
  end
  has_and_belongs_to_many :rooms
  has_many :messages, ->{ order("created_at DESC") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def create
    Message.create(create_params)
    redirect_to controller: :rooms, action: :show, id: params[:room_id]
  end

  private
  def create_params
    params.require(:message).permit(:text).merge(user_id: current_user.id, room_id: params[:room_id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def new
    @users = User.all
    @room = Room.new
  end

  def create
    tmp = create_params
    tmp["id"].delete("")
    ids = tmp["id"].map {|tmp| tmp.to_i}
    ids << current_user.id
    @room = Room.new
    key = tmp[:key]
    if tmp[:key] != ""
      @room.key = key
    end
    # 登録済み処理
    # exist = false
    # existing_rooms = Room.includes(:users).where( 'users.id' => current_user.id )
    # existing_room = nil
    # existing_rooms.each do |room|
    #   existing_user_ids =  User.includes(:rooms).where( 'rooms.id' => room.id ).ids
    #   if existing_user_ids == ids
    #     exist = true
    #     existing_room = @room
    #   end
    # end
    # binding.pry
    # if exist == true
    #   redirect_to :new_room, alert: '既に作成済みです' and return
    if @room.save
      @room.users << User.find(ids)
      redirect_to action: :show, id: @room.id
    else
      redirect_to :new_room, alert: 'ルーム名を入力してください'
    end

  end

  def show
    @room = Room.find(params[:id])
    @message = Message.new
    @messages = @room.messages
  end

  def edit
    @room = Room.find(params[:id])
  end

    private
  def create_params
    params.require(:user).permit(id: []).merge(params.require(:room).permit(:key))
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def rooms_list
    # binding.pry
    @rooms = User.find(params[:id]).rooms
  end

  def friends_list
    user = User.all
    @users = user.where.not(name: nil)
    # binding.pry
  end

  def update
    current_user.update(update_params)
  end

  def update_params
    params.require(:user).permit(:name, :user_id, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/common/_header.html.erb
<% if user_signed_in? %>
  <div class='navbar navbar-default navbar-fixed-top'>
    <div class='container'>
      <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-responsive-collapse'>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      <%= link_to "#{user_path(current_user)}/rooms_list", :class => 'navbar-brand' do %>
        <%= image_tag 'logo.png' %> <small class='hidden-xs hidden-sm'>いつでもどこでも無料メール</small>
      <% end %>
      <div class='navbar-collapse collapse navbar-responsive-collapse navbar-right'>
        <ul class='nav navbar-nav'>
          <li class='dropdown'>
            <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>ルーム <span class='caret'></span></a>
            <ul class='dropdown-menu' role='menu'>
               <li><%= link_to "一覧", "#{user_path(current_user)}/rooms_list" %></li>
              <li><%= link_to "新規" , new_room_path %></li>
            </ul>
          </li>
                    <li class='dropdown'>
            <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>フレンズ<span class='caret'></span></a>
            <ul class='dropdown-menu' role='menu'>
               <li><%= link_to "一覧", "#{user_path(current_user)}/friends_list" %></li>
            </ul>
          </li>
          <li class='dropdown'>
            <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>アカウント <span class='caret'></span></a>
            <ul class='dropdown-menu' role='menu'>
              <li><%= link_to "マイページ", user_path(current_user) %></li>
               <li><%= link_to "プロフィール編集", edit_user_path(current_user) %></li>
              <li><%= link_to "ログアウト" , destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/common/_login_logo.html.erb
<div class='sign_up_logo'>
  <%= image_tag 'logo.png' %>
  <small>いつでもどこでも無料メール</small>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='ja'>
  <head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=Edge,chrome=1'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title>Fline</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>
  <body>
    <script type='text/javascript' charset='utf-8'>
      $(function(){
        $.material.init();
      });
    </script>
    <%= render partial: 'common/header' %>
    <div class='container'>
      <div class='row'>
        <div class='col-lg-12'>
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>
      <footer class='row text-center'>
        <p>(C) Fline 2017</p>
      </footer>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="question_content top_content">
  <header class="question_header">
    <div class="question_image icon_image" style="background-image: url(<%= message.user.avatar.url(:medium) %>);"></div>
    <div class="question_user_info user_info">
      <span><%= link_to message.user.name, user_path(message.user) %></span>
      <time><%= time_ago_in_words message.created_at %></time>
    </div>
  </header>
  <div class="question_body">
    <div class="question_box">
      <span class="question_text"><%= message.text %></span>
    </div>
  </div>
</div>

app/views/rooms/edit.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3>Member List</h3>
    <div class="list-group">
    <% @room.users.each do |user| %>
      <% if user != current_user %>
        <div class="list-group-item"><%= link_to user.name, user_path(user) %><hr></div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<h2>ルームメンバーを選択し、ルーム名を決めてください</h2>
<div class="row form user_profile">
  <%= form_for @room do |f| %>
    <%= hidden_field_tag 'user[id][]' %>
  <% @users.each do |i| %>
  <% if i == current_user or i.name.nil? %>
    <% next %>
    <% end %>
    <p>
      <%= "#{i.name}" =%>
      <%= check_box_tag 'user[id][]', i.id, checked = false, :id => "user_#{i.id}" %>
    </p><hr>
  <% end %>
  <div class='form-group'>
  <%= f.label :ルーム名 %><br />
  <%= f.text_field :key, placeholder: 'ルーム名を入力(必須)' ,class: 'form-control' %>
  </div>
  <%= submit_tag "ルーム作成" , { class: "btn btn-lg btn-primary withripple" } %>
  <% end %>
</div>

app/views/rooms/show.html.erb
<h2><%= link_to @room.key, edit_room_path(@room) =%><span class='caret'></span></h2>
<%= render partial: "messages/message", collection: @messages %>
  <div class='navibar navbar-default navbar-fixed-bottom'>
    <div class="posting_form top_content">
    <header class="posting_header">
      <div class="posting_image icon_image" style="background-image: url(<%= current_user.avatar.url(:medium) %>);"></div>
      <div class="posting_user_info user_info">
        <%= current_user.name %>
      </div>
    </header>
    <%= form_for([@room, @message]) do |f| %>
      <%= f.text_field :text, placeholder: "メッセージを入力" %>
      <%= f.submit "送信" %>
    <% end %>
  </div>
  </div>

app/views/top/index.html.erb
<% unless current_user.full_profile? %>
  <header class="header_top panel panel-default col-lg-12 no-profile">
    <h2>まずは、あなたの基本プロフィールを登録しましょう</h2>
    <%= link_to "プロフィールを登録する", edit_user_path(current_user), { class: "btn btn-lg btn-primary withripple" } %>
  </header>
<% else %>
<% end %>

app/views/users/edit.html.erb
<div class="row form">
  <div class="col-lg-12">
    <%= form_for current_user do |f| %>
      <h2>プロフィール画像</h2>
      <div class="form-group file">
        <%= f.file_field :avatar, class: "form-control floating-label", placeholder: "画像アップロード" %>
      </div>
      <h2>登録情報</h2>
      <div class="form-group">
        <div class="col-lg-6">
          <%= f.text_field :name, placeholder: "名前", class: "form-control" %>
        </div>
        <div class="col-lg-6">
          <%= f.text_field :user_id, placeholder: "ID", class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit "送信", class: "btn btn-primary withripple" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/friends_list.html.erb
<h2>友だちリスト</h2>
<div class="row form user_profile">
  <% @users.each do |user| %>
  <% if user != current_user %>
    <%= link_to user.name, user_path(user) %><hr>
    <% end %>
  <% end %>
</div>

app/views/users/rooms_list.html.erb
<h2>ルームリスト</h2>
<div class="row form">
  <% @rooms.each do |room| %>
  <%= link_to room.key, room_path(room) %><hr>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="row form user_profile">
  <div class="col-lg-12">
  <div class="image" style="background-image: url(<%= @user.avatar.url(:medium) %>);"></div>
    <h2><%= "#{@user.name}" %><span><%= "ID: #{@user.user_id}" %></span></h2>
    <% if current_user.id == @user.id %>
      <div class="profile_edit">
        <%= link_to "プロフィール編集", edit_user_path(current_user), {:class => "btn btn-primary withripple" }%>
      </div>
    <% end %>
  </div>
</div>

app/views/users/update.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3>プロフィールの編集が完了しました。</h3>
    <%= link_to "ホームに戻る", "#{user_path(current_user)}/friends_list" %>
  </div>
</div>